name: Release

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to publish a release for (eg. v0.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.git_tag }}'

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish to NPM
        run: |
          make ci
          echo ""
          echo "Publishing"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
